Minor changes
- Added second XorString code to the header file
- Discovered it works fine in VS 2015, but not 2013 (however, using it
in 2015 gives "error C2397: conversion from 'float' to 'DWORD' requires
a narrowing conversion" in ent-enums relating to clan logos).
- Had to truncate the title into 2 strings due to char limit on Xor
function.
- If header file commented out/not used - no narrowing conversion error.
No idea how it's related in any way.